state = {}
love.filesystem.require("states/menu.lua")
love.filesystem.require("states/game.lua")
love.filesystem.require("states/options.lua")
love.filesystem.require("states/pause.lua")
love.filesystem.require("states/victory.lua")
love.filesystem.require("states/loss.lua")
love.filesystem.require("states/help.lua")
love.filesystem.require("states/repl.lua")
love.filesystem.require("states/inventory.lua")
love.filesystem.require("states/highscores.lua")
